[mysqld]
# 설치 폴더 및 데이터 폴더 지정 (경로에 맞게 수정)
#basedir=.
datadir=./data

# 기존 DB와 충돌하지 않도록 다른 포트 사용 (예: 3307)
port=3307

# 파이프/소켓 이름도 다르게 지정하여 충돌 방지
socket=mariadb_portable.sock
#shared-memory-base-name=mariadb_portable

# (선택) 외부 접속 허용 시
bind-address=0.0.0.0
