// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbTF_qd7A-82Dmy9kSrNd9whgHBSWY1Mk',
    appId: '1:112328233861:web:3ec69fa7bc391415196aec',
    messagingSenderId: '112328233861',
    projectId: 'furynote',
    authDomain: 'furynote.firebaseapp.com',
    storageBucket: 'furynote.firebasestorage.app',
    measurementId: 'G-FZPNK10XCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY4G16LuS6nlpspds3Ui1DyxmK7sL_Vx4',
    appId: '1:112328233861:android:5ab770d4c7f4f27e196aec',
    messagingSenderId: '112328233861',
    projectId: 'furynote',
    storageBucket: 'furynote.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1GqxxQ7tOL4AafoD_V7LKv7Wz-hV67Zc',
    appId: '1:112328233861:ios:60a9d04a92c23ea6196aec',
    messagingSenderId: '112328233861',
    projectId: 'furynote',
    storageBucket: 'furynote.firebasestorage.app',
    iosBundleId: 'kr.co.lunlu.furynote',
  );
}
